spring.application.name=LectureMensuelle
server.port=8090
spring.datasource.url=jdbc:h2:mem:students-db
spring.h2.console.enabled=true


security.jwt.secret-key =${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000


spring.config.import=optional:file:.env[.properties]